apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  labels: 
    k8s-app: node-web-app
  name: node-web-app
  namespace: k8s-demo
spec: 
  replicas: 1
  strategy: 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        k8s-app: node-web-app
    spec: 
      containers: 
        - 
          image: "azatsarynnyy/node-web-app:latest"
          imagePullPolicy: Always
          name: node-web-app
          ports: 
            - 
              containerPort: 8080
              name: app-port
              protocol: TCP
